### ISSUE TITLE
Problema ao consultar estado da saga, alteração da versão da saga ao consultar o estado gera erro ao transacionar para outro estado

### ISSUE THREAD

**Issue by JulioSCr** [JulioSCr/Saga.Orchestrator#1]

**Comment by JulioSCr** [comment]
Erro observado ao consultar estado de uma saga enquanto ela transaciona para outro estado.

`warn: MassTransit.ReceiveTransport[0]
      R-RETRY rabbitmq://localhost/full-export-state 08970000-060c-b445-12b6-08dc4a6c5762 MassTransit.RetryPolicies.RetryConsumeContext<Saga.Orchestrator.Worker.Application.Events.IBasicDataSent>
      MassTransit.SagaException: Saga.Orchestrator.Worker.Application.StateMachines.FullExportState(cf6cf700-5b76-4f9f-bd27-c7b314169988) Saga exception: Saga update failed
       ---> MassTransit.RedisSagaConcurrencyException: Saga.Orchestrator.Worker.Application.StateMachines.FullExportState(cf6cf700-5b76-4f9f-bd27-c7b314169988) Saga exception: Saga version conflict
         at MassTransit.RedisIntegration.Saga.RedisDatabaseContext`1.Update(SagaConsumeContext`1 context) in /_/src/Persistence/MassTransit.RedisIntegration/RedisIntegration/Saga/RedisDatabaseContext.cs:line 59
         --- End of inner exception stack trace ---
         at MassTransit.RedisIntegration.Saga.RedisDatabaseContext`1.Update(SagaConsumeContext`1 context) in /_/src/Persistence/MassTransit.RedisIntegration/RedisIntegration/Saga/RedisDatabaseContext.cs:line 65
         at MassTransit.RedisIntegration.Saga.RedisDatabaseContext`1.Update(SagaConsumeContext`1 context) in /_/src/Persistence/MassTransit.RedisIntegration/RedisIntegration/Saga/RedisDatabaseContext.cs:line 70
         at MassTransit.Middleware.SendSagaPipe`2.Send(SagaRepositoryContext`2 context) in /_/src/MassTransit/Middleware/SendSagaPipe.cs:line 56
         at MassTransit.Middleware.SendSagaPipe`2.Send(SagaRepositoryContext`2 context) in /_/src/MassTransit/Middleware/SendSagaPipe.cs:line 67
         at MassTransit.RedisIntegration.Saga.RedisSagaRepositoryContextFactory`1.Send[T](ConsumeContext`1 context, IPipe`1 next) in /_/src/Persistence/MassTransit.RedisIntegration/RedisIntegration/Saga/RedisSagaRepositoryContextFactory.cs:line 78
         at MassTransit.RedisIntegration.Saga.RedisSagaRepositoryContextFactory`1.Send[T](ConsumeContext`1 context, IPipe`1 next) in /_/src/Persistence/MassTransit.RedisIntegration/RedisIntegration/Saga/RedisSagaRepositoryContextFactory.cs:line 82
         at MassTransit.DependencyInjection.DependencyInjectionSagaRepositoryContextFactory`1.Send[T](ConsumeContext`1 context, Func`3 send) in /_/src/MassTransit/DependencyInjection/DependencyInjection/DependencyInjectionSagaRepositoryContextFactory.cs:line 87
         at MassTransit.DependencyInjection.DependencyInjectionSagaRepositoryContextFactory`1.Send[T](ConsumeContext`1 context, Func`3 send) in /_/src/MassTransit/DependencyInjection/DependencyInjection/DependencyInjectionSagaRepositoryContextFactory.cs:line 96
         at MassTransit.Middleware.CorrelatedSagaFilter`2.Send(ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/Middleware/CorrelatedSagaFilter.cs:line 45
         at MassTransit.Middleware.CorrelatedSagaFilter`2.Send(ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/Middleware/CorrelatedSagaFilter.cs:line 62
         at MassTransit.Middleware.ConsumeConcurrencyLimitFilter`1.Send(ConsumeContext`1 context, IPipe`1 next) in /_/src/MassTransit/Middleware/ConsumeConcurrencyLimitFilter.cs:line 28
         at MassTransit.Middleware.InMemoryOutboxFilter`2.Send(TContext context, IPipe`1 next) in /_/src/MassTransit/Middleware/InMemoryOutboxFilter.cs:line 35
         at MassTransit.Middleware.InMemoryOutboxFilter`2.Send(TContext context, IPipe`1 next) in /_/src/MassTransit/Middleware/InMemoryOutboxFilter.cs:line 45
         at MassTransit.Middleware.RetryFilter`1.MassTransit.IFilter<TContext>.Send(TContext context, IPipe`1 next) in /_/src/MassTransit/Middleware/RetryFilter.cs:line 47`
